### ISSUE TITLE
Instructions For Docker Compose Using 'ghcr.io' Docker Based Image For Kiwix?

### ISSUE THREAD

**Issue by SamuelBanya** [kiwix/overview#91]
**EDIT:**
- I included some updated config files below, but still am having issues

Hello there,

I have been in the process of trying to deploy a Kiwix instance on a Raspberry Pi 3B+ running Armbian.
That being noted, it was hard to find the fact that there's still a Docker container image for 'Kiwix' itself.

Is there any way that your team update your website to include a 'Containers' section so others can easily find it? I say this because I had to dig on your site to find the post (https://www.kiwix.org/en/our-docker-images-are-on-ghcr-io/), but it really should just have a server section on the Kiwix page itself for people that want to host their own Kiwix instance (https://www.kiwix.org/en/download/) instead of having to make a user look on the 'Releases' section of the GitHub page itself.

That being noted, I tried to use the following two links as references for creating a Docker Compose file to deploy Kiwix but am having issues with it so far:
- https://noted.lol/setup-and-install-kiwix-serve-on-debian-systems/
- https://thehomelab.wiki/books/docker/page/setup-and-install-kiwix-serve-on-debian-systems

On the Pi itself, I basically just created a '/home/pi/kiwix/data' directory that contains the following older Wikipedia .ZIM file rips:
```
~/kiwix/data$ pwd
/home/pi/kiwix/data

~/kiwix/data$ ls
wikipedia_en_wp1-0.5_2007-03.zim  wikipedia_en_wp1-0.7_2009-05.zim  wikipedia_en_wp1-0.8_orig_2010-12.zim
```

This is my Docker compose file so far that I tried within my Portainer instance on the Pi itself:
```
version: '3'

services:
  kiwix-serve:
    image: ghcr.io/kiwix/kiwix-serve
    volumes:
      - /home/pi/kiwix/data:/data
    ports:
      - '8080:80'
    command:
      wikipedia_en_wp1-0.5_2007-03.zim  
      wikipedia_en_wp1-0.7_2009-05.zim  
      wikipedia_en_wp1-0.8_orig_2010-12.zim
```

I am unable to see the Kiwix image actually run on a specific port and it is currently in 'Exited' status on Portainer.

These are the logs I'm receiving after attempting to deploy it:
```
/usr/local/bin/kiwix-serve --port=8080 wikipedia_en_wp1-0.5_2007-03.zim wikipedia_en_wp1-0.7_2009-05.zim wikipedia_en_wp1-0.8_orig_2010-12.zim

Unable to add the ZIM file 'wikipedia_en_wp1-0.5_2007-03.zim' to the internal library.

Here is the content of /data:

/data/wikipedia_en_wp1-0.7_2009-05.zim

/data/wikipedia_en_wp1-0.5_2007-03.zim

/data/wikipedia_en_wp1-0.8_orig_2010-12.zim
```

Thanks!

**Comment by SamuelBanya** [comment]
Still failing, but related update:

I tried just using one single .ZIM file at a time to see if it was the .ZIM file rips that I got that were part of the issue.

The second .ZIM file (2009 rip) started it for a brief second and a half, and then still exited with roughly the same error as above.

I mention this because I thought maybe it was because I shouldn't add so many .ZIM files in the 'commands' section since they probably need an array or something equivalent for Docker config files.

Is there something wrong with my current Docker compose file syntax above in that case?

Latest Docker Compose file:
```
version: '3'

services:
  kiwix-serve:
    image: ghcr.io/kiwix/kiwix-serve
    volumes:
      - /home/pi/kiwix/data:/data
    ports:
      - '8080:80'
    command:
      wikipedia_en_wp1-0.7_2009-05.zim  
```

Latest logs:
```
/usr/local/bin/kiwix-serve --port=8080 wikipedia_en_wp1-0.7_2009-05.zim

Unable to add the ZIM file 'wikipedia_en_wp1-0.7_2009-05.zim' to the internal library.

Here is the content of /data:

/data/wikipedia_en_wp1-0.7_2009-05.zim

/data/wikipedia_en_wp1-0.5_2007-03.zim

/data/wikipedia_en_wp1-0.8_orig_2010-12.zim
```

**Comment by SamuelBanya** [comment]
**Latest update:**
- Just to isolate the .ZIM files I have, I did try to use the latest Arch Linux wiki .ZIM file, and it appears to be running though... the Pi's IP + 8080 isn't working, ex: "blah.blah.blah.blah:8080" doesn't seem to show Kiwix in a browser tab on Firefox.
- This being noted, are old Wikipedia rips not compatible?
- Also, why isn't the IP address + port 8080 good enough to show Kiwix in a browser from the docker container image itself?



Here's the latest Docker compose file I have:

```
version: '3'

services:
  kiwix-serve:
    image: ghcr.io/kiwix/kiwix-serve
    volumes:
      - /home/pi/kiwix/data:/data
    ports:
      - '8080:80'
    command:
      archlinux_en_all_maxi_2022-12.zim
```
